"""Add pipeline and job fields

Revision ID: 7c14a74f1906
Revises: aae39fa84135
Create Date: 2026-07-14 20:32:37.958021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c14a74f1906'
down_revision: Union[str, Sequence[str], None] = 'aae39fa84135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "jobs",
        sa.Column(
            "current_stage",
            sa.String(length=30),
            nullable=False,
            server_default="ACQUISITION",
        ),
    )

    op.add_column(
        "jobs",
        sa.Column(
            "total_records",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "jobs",
        sa.Column(
            "execution_time_ms",
            sa.Integer(),
            nullable=True,
        ),
    )

    op.add_column(
        "jobs",
        sa.Column(
            "file_checksum",
            sa.String(length=64),
            nullable=True,
        ),
    )

    op.add_column(
        "jobs",
        sa.Column(
            "archive_path",
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.add_column(
        "jobs",
        sa.Column(
            "job_log",
            sa.Text(),
            nullable=True,
        ),
    )

    op.alter_column("jobs", "current_stage", server_default=None)
    op.alter_column("jobs", "total_records", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'job_log')
    op.drop_column('jobs', 'archive_path')
    op.drop_column('jobs', 'file_checksum')
    op.drop_column('jobs', 'execution_time_ms')
    op.drop_column('jobs', 'total_records')
    op.drop_column('jobs', 'current_stage')
    # ### end Alembic commands ###
