"""Add pipeline configuration fields

Revision ID: aae39fa84135
Revises: 3d61112fbc9a
Create Date: 2026-07-14 20:25:49.736956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae39fa84135'
down_revision: Union[str, Sequence[str], None] = '3d61112fbc9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('schedule', sa.String(length=100), nullable=True))
    op.add_column('pipelines', sa.Column('decoder_type', sa.String(length=50), nullable=False))
    op.add_column('pipelines', sa.Column('output_format', sa.String(length=20), nullable=False))
    op.add_column('pipelines', sa.Column('archive_enabled', sa.Boolean(), nullable=False))
    op.add_column('pipelines', sa.Column('retry_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'retry_count')
    op.drop_column('pipelines', 'archive_enabled')
    op.drop_column('pipelines', 'output_format')
    op.drop_column('pipelines', 'decoder_type')
    op.drop_column('pipelines', 'schedule')
    # ### end Alembic commands ###
